[build]
builder = "Dockerfile"
buildPath = "kitchen-compass-sln"
dockerfilePath = "kitchen-compass-sln/CustomerBackend/Dockerfile"

[deploy]
start = "dotnet CustomerBackend.dll"
restartPolicyType = "never"
