[build]
builder = "Dockerfile"
dockerfilePath = "./kitchen-compass-sln/CustomerBackend/Dockerfile"
buildPath = "./kitchen-compass-sln"

[deploy]
start = "dotnet CustomerBackend.dll"
restartPolicyType = "never"
